/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tris;

import java.awt.Color;
import javax.swing.JRootPane;

/**
 *
 * @author matte
 */
public class TrisForm extends javax.swing.JFrame {

    Tris t = new Tris();
    private int i = 0;
    private boolean attivato = false;

    /**
     * Creates new form TrisForm
     */
    public TrisForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitolo = new javax.swing.JLabel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        lblRisultato = new javax.swing.JLabel();
        lblRestart = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 650));

        lblTitolo.setFont(new java.awt.Font("Impact", 1, 72)); // NOI18N
        lblTitolo.setForeground(new java.awt.Color(255, 0, 0));
        lblTitolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitolo.setText("TRIS");

        btn1.setFont(new java.awt.Font("Arial", 1, 80)); // NOI18N
        btn1.setPreferredSize(new java.awt.Dimension(100, 100));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setFont(new java.awt.Font("Arial", 1, 80)); // NOI18N
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setFont(new java.awt.Font("Arial", 1, 80)); // NOI18N
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.setFont(new java.awt.Font("Arial", 1, 80)); // NOI18N
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.setFont(new java.awt.Font("Arial", 1, 80)); // NOI18N
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.setFont(new java.awt.Font("Arial", 1, 80)); // NOI18N
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn7.setFont(new java.awt.Font("Arial", 1, 80)); // NOI18N
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setFont(new java.awt.Font("Arial", 1, 80)); // NOI18N
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setFont(new java.awt.Font("Arial", 1, 80)); // NOI18N
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        lblRisultato.setFont(new java.awt.Font("Impact", 1, 48)); // NOI18N
        lblRisultato.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblRestart.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblRestart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRestart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRestartMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRisultato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(119, 119, 119)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btn3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(126, 126, 126))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(307, 307, 307)
                        .addComponent(lblTitolo, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(lblRestart, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblTitolo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRisultato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRestart, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        t.riempiCampo();
        if (i % 2 == 0) {
            i++;
            btn1.setText("X");
            btn1.setForeground(Color.black);
            btn1.setEnabled(false);
            if (t.giocatore1(0, 0) == true) {

            }
        } else {
            btn1.setText("O");
            i++;
            btn1.setForeground(Color.red);
            btn1.setEnabled(false);
            if (t.giocatore2(0, 0)) {

            }
        }

        if (t.controllaVintoG1() == true) {
            lblRisultato.setText("VINCE GIOCATORE 1");
            btn2.setEnabled(false);
            btn3.setEnabled(false);
            btn4.setEnabled(false);
            btn5.setEnabled(false);
            btn6.setEnabled(false);
            btn7.setEnabled(false);
            btn8.setEnabled(false);
            btn9.setEnabled(false);
            
            attivato = true;
            lblRestart.setText("PREMERE QUI PER GIOCARE ANCORA");
        } else if (t.controllaVintoG2() == true) {
            lblRisultato.setText("VINCE GIOCATORE 2");
            lblRisultato.setForeground(Color.red);
            btn2.setEnabled(false);
            btn3.setEnabled(false);
            btn4.setEnabled(false);
            btn5.setEnabled(false);
            btn6.setEnabled(false);
            btn7.setEnabled(false);
            btn8.setEnabled(false);
            btn9.setEnabled(false);
            
            attivato = true;
            lblRestart.setText("PREMERE QUI PER GIOCARE ANCORA");
        } else if(i == 9){
            lblRisultato.setText("PAREGGIO");
            attivato = true;
            lblRestart.setText("PREMERE QUI PER GIOCARE ANCORA");
        }
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        t.riempiCampo();
        if (i % 2 == 0) {
            i++;
            btn2.setText("X");
            btn2.setForeground(Color.black);
            btn2.setEnabled(false);
            if (t.giocatore1(0, 1)) {

            }
        } else {
            btn2.setText("O");
            i++;
            btn2.setForeground(Color.red);
            btn2.setEnabled(false);
            if (t.giocatore2(0, 1)) {

            }
        }

        if (t.controllaVintoG1() == true) {
            lblRisultato.setText("VINCE GIOCATORE 1");
            btn1.setEnabled(false);
            btn2.setEnabled(false);
            btn3.setEnabled(false);
            btn4.setEnabled(false);
            btn5.setEnabled(false);
            btn6.setEnabled(false);
            btn7.setEnabled(false);
            btn8.setEnabled(false);
            btn9.setEnabled(false);
            
            attivato = true;
            lblRestart.setText("PREMERE QUI PER GIOCARE ANCORA");
        } else if (t.controllaVintoG2() == true) {
            lblRisultato.setText("VINCE GIOCATORE 2");
            lblRisultato.setForeground(Color.red);
            btn1.setEnabled(false);
            btn2.setEnabled(false);
            btn3.setEnabled(false);
            btn4.setEnabled(false);
            btn5.setEnabled(false);
            btn6.setEnabled(false);
            btn7.setEnabled(false);
            btn8.setEnabled(false);
            btn9.setEnabled(false);
            
            attivato = true;
            lblRestart.setText("PREMERE QUI PER GIOCARE ANCORA");
        } else if(i == 9){
            lblRisultato.setText("PAREGGIO");
            attivato = true;
            lblRestart.setText("PREMERE QUI PER GIOCARE ANCORA");
        }
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        t.riempiCampo();
        if (i % 2 == 0) {
            i++;
            btn3.setText("X");
            btn3.setForeground(Color.black);
            btn3.setEnabled(false);
            if (t.giocatore1(0, 2)) {

            }
        } else {
            btn3.setText("O");
            i++;
            btn3.setForeground(Color.red);
            btn3.setEnabled(false);
            if (t.giocatore2(0, 2)) {

            }
        }

        if (t.controllaVintoG1() == true) {
            lblRisultato.setText("VINCE GIOCATORE 1");
            btn1.setEnabled(false);
            btn2.setEnabled(false);
            btn3.setEnabled(false);
            btn4.setEnabled(false);
            btn5.setEnabled(false);
            btn6.setEnabled(false);
            btn7.setEnabled(false);
            btn8.setEnabled(false);
            btn9.setEnabled(false);
            
            attivato = true;
            lblRestart.setText("PREMERE QUI PER GIOCARE ANCORA");
        } else if (t.controllaVintoG2() == true) {
            lblRisultato.setText("VINCE GIOCATORE 2");
            lblRisultato.setForeground(Color.red);
            btn1.setEnabled(false);
            btn2.setEnabled(false);
            btn3.setEnabled(false);
            btn4.setEnabled(false);
            btn5.setEnabled(false);
            btn6.setEnabled(false);
            btn7.setEnabled(false);
            btn8.setEnabled(false);
            btn9.setEnabled(false);
            
            attivato = true;
            lblRestart.setText("PREMERE QUI PER GIOCARE ANCORA");
        } else if(i == 9){
            lblRisultato.setText("PAREGGIO");
            attivato = true;
            lblRestart.setText("PREMERE QUI PER GIOCARE ANCORA");
        }
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        t.riempiCampo();
        if (i % 2 == 0) {
            i++;
            btn4.setText("X");
            btn4.setForeground(Color.black);
            btn4.setEnabled(false);
            if (t.giocatore1(1, 0)) {

            }
        } else {
            btn4.setText("O");
            i++;
            btn4.setForeground(Color.red);
            btn4.setEnabled(false);
            if (t.giocatore2(1, 0)) {

            }
        }

        if (t.controllaVintoG1() == true) {
            lblRisultato.setText("VINCE GIOCATORE 1");
            btn1.setEnabled(false);
            btn2.setEnabled(false);
            btn3.setEnabled(false);
            btn4.setEnabled(false);
            btn5.setEnabled(false);
            btn6.setEnabled(false);
            btn7.setEnabled(false);
            btn8.setEnabled(false);
            btn9.setEnabled(false);
            
            attivato = true;
            lblRestart.setText("PREMERE QUI PER GIOCARE ANCORA");
        } else if (t.controllaVintoG2() == true) {
            lblRisultato.setText("VINCE GIOCATORE 2");
            lblRisultato.setForeground(Color.red);
            btn1.setEnabled(false);
            btn2.setEnabled(false);
            btn3.setEnabled(false);
            btn4.setEnabled(false);
            btn5.setEnabled(false);
            btn6.setEnabled(false);
            btn7.setEnabled(false);
            btn8.setEnabled(false);
            btn9.setEnabled(false);
            
            attivato = true;
            lblRestart.setText("PREMERE QUI PER GIOCARE ANCORA");
        } else if(i == 9){
            lblRisultato.setText("PAREGGIO");
            attivato = true;
            lblRestart.setText("PREMERE QUI PER GIOCARE ANCORA");
        }
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        t.riempiCampo();
        if (i % 2 == 0) {
            i++;
            btn5.setText("X");
            btn5.setForeground(Color.black);
            btn5.setEnabled(false);
            if (t.giocatore1(1, 1)) {

            }
        } else {
            btn5.setText("O");
            i++;
            btn5.setForeground(Color.red);
            btn5.setEnabled(false);
            if (t.giocatore2(1, 1)) {

            }
        }

        if (t.controllaVintoG1() == true) {
            lblRisultato.setText("VINCE GIOCATORE 1");
            btn1.setEnabled(false);
            btn2.setEnabled(false);
            btn3.setEnabled(false);
            btn4.setEnabled(false);
            btn5.setEnabled(false);
            btn6.setEnabled(false);
            btn7.setEnabled(false);
            btn8.setEnabled(false);
            btn9.setEnabled(false);
            
            attivato = true;
            lblRestart.setText("PREMERE QUI PER GIOCARE ANCORA");
        } else if (t.controllaVintoG2() == true) {
            lblRisultato.setText("VINCE GIOCATORE 2");
            lblRisultato.setForeground(Color.red);
            btn1.setEnabled(false);
            btn2.setEnabled(false);
            btn3.setEnabled(false);
            btn4.setEnabled(false);
            btn5.setEnabled(false);
            btn6.setEnabled(false);
            btn7.setEnabled(false);
            btn8.setEnabled(false);
            btn9.setEnabled(false);
            
            attivato = true;
            lblRestart.setText("PREMERE QUI PER GIOCARE ANCORA");
        } else if(i == 9){
            lblRisultato.setText("PAREGGIO");
            attivato = true;
            lblRestart.setText("PREMERE QUI PER GIOCARE ANCORA");
        }
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        t.riempiCampo();
        if (i % 2 == 0) {
            i++;
            btn6.setText("X");
            btn6.setForeground(Color.black);
            btn6.setEnabled(false);
            if (t.giocatore1(1, 2)) {

            }
        } else {
            btn6.setText("O");
            i++;
            btn6.setForeground(Color.red);
            btn6.setEnabled(false);
            if (t.giocatore2(1, 2)) {

            }
        }

        if (t.controllaVintoG1() == true) {
            lblRisultato.setText("VINCE GIOCATORE 1");
            btn1.setEnabled(false);
            btn2.setEnabled(false);
            btn3.setEnabled(false);
            btn4.setEnabled(false);
            btn5.setEnabled(false);
            btn6.setEnabled(false);
            btn7.setEnabled(false);
            btn8.setEnabled(false);
            btn9.setEnabled(false);
            
            attivato = true;
            lblRestart.setText("PREMERE QUI PER GIOCARE ANCORA");
        } else if (t.controllaVintoG2() == true) {
            lblRisultato.setText("VINCE GIOCATORE 2");
            lblRisultato.setForeground(Color.red);
            btn1.setEnabled(false);
            btn2.setEnabled(false);
            btn3.setEnabled(false);
            btn4.setEnabled(false);
            btn5.setEnabled(false);
            btn6.setEnabled(false);
            btn7.setEnabled(false);
            btn8.setEnabled(false);
            btn9.setEnabled(false);
            
            attivato = true;
            lblRestart.setText("PREMERE QUI PER GIOCARE ANCORA");
        } else if(i == 9){
            lblRisultato.setText("PAREGGIO");
            attivato = true;
            lblRestart.setText("PREMERE QUI PER GIOCARE ANCORA");
        }
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        t.riempiCampo();
        if (i % 2 == 0) {
            i++;
            btn8.setText("X");
            btn8.setForeground(Color.black);
            btn8.setEnabled(false);
            if (t.giocatore1(2, 1)) {

            }
        } else {
            btn8.setText("O");
            i++;
            btn8.setForeground(Color.red);
            btn8.setEnabled(false);
            if (t.giocatore2(2, 1)) {

            }
        }

        if (t.controllaVintoG1() == true) {
            lblRisultato.setText("VINCE GIOCATORE 1");
            btn1.setEnabled(false);
            btn2.setEnabled(false);
            btn3.setEnabled(false);
            btn4.setEnabled(false);
            btn5.setEnabled(false);
            btn6.setEnabled(false);
            btn7.setEnabled(false);
            btn8.setEnabled(false);
            btn9.setEnabled(false);
            
            attivato = true;
            lblRestart.setText("PREMERE QUI PER GIOCARE ANCORA");
        } else if (t.controllaVintoG2() == true) {
            lblRisultato.setText("VINCE GIOCATORE 2");
            lblRisultato.setForeground(Color.red);
            btn1.setEnabled(false);
            btn2.setEnabled(false);
            btn3.setEnabled(false);
            btn4.setEnabled(false);
            btn5.setEnabled(false);
            btn6.setEnabled(false);
            btn7.setEnabled(false);
            btn8.setEnabled(false);
            btn9.setEnabled(false);
            
            attivato = true;
            lblRestart.setText("PREMERE QUI PER GIOCARE ANCORA");
        } else if(i == 9){
            lblRisultato.setText("PAREGGIO");
            attivato = true;
            lblRestart.setText("PREMERE QUI PER GIOCARE ANCORA");
        }
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        t.riempiCampo();
        if (i % 2 == 0) {
            i++;
            btn9.setText("X");
            btn9.setForeground(Color.black);
            btn9.setEnabled(false);
            if (t.giocatore1(2, 2)) {

            }
        } else {
            btn9.setText("O");
            i++;
            btn9.setForeground(Color.red);
            btn9.setEnabled(false);
            if (t.giocatore2(2, 2)) {

            }
        }

        if (t.controllaVintoG1() == true) {
            lblRisultato.setText("VINCE GIOCATORE 1");
            btn1.setEnabled(false);
            btn2.setEnabled(false);
            btn3.setEnabled(false);
            btn4.setEnabled(false);
            btn5.setEnabled(false);
            btn6.setEnabled(false);
            btn7.setEnabled(false);
            btn8.setEnabled(false);
            btn9.setEnabled(false);
            
            attivato = true;
            lblRestart.setText("PREMERE QUI PER GIOCARE ANCORA");
        } else if (t.controllaVintoG2() == true) {
            lblRisultato.setText("VINCE GIOCATORE 2");
            lblRisultato.setForeground(Color.red);
            btn1.setEnabled(false);
            btn2.setEnabled(false);
            btn3.setEnabled(false);
            btn4.setEnabled(false);
            btn5.setEnabled(false);
            btn6.setEnabled(false);
            btn7.setEnabled(false);
            btn8.setEnabled(false);
            btn9.setEnabled(false);
            
            attivato = true;
            lblRestart.setText("PREMERE QUI PER GIOCARE ANCORA");
        } else if(i == 9){
            lblRisultato.setText("PAREGGIO");
            attivato = true;
            lblRestart.setText("PREMERE QUI PER GIOCARE ANCORA");
        }
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        t.riempiCampo();
        if (i % 2 == 0) {
            i++;
            btn7.setText("X");
            btn7.setForeground(Color.black);
            btn7.setEnabled(false);
            if (t.giocatore1(2, 0)) {

            }
        } else {
            btn7.setText("O");
            i++;
            btn7.setForeground(Color.red);
            btn7.setEnabled(false);
            if (t.giocatore2(2, 0)) {

            }
        }

        if (t.controllaVintoG1() == true) {
            lblRisultato.setText("VINCE GIOCATORE 1");
            btn1.setEnabled(false);
            btn2.setEnabled(false);
            btn3.setEnabled(false);
            btn4.setEnabled(false);
            btn5.setEnabled(false);
            btn6.setEnabled(false);
            btn7.setEnabled(false);
            btn8.setEnabled(false);
            btn9.setEnabled(false);
            
            attivato = true;
            lblRestart.setText("PREMERE QUI PER GIOCARE ANCORA");
        } else if (t.controllaVintoG2() == true) {
            lblRisultato.setText("VINCE GIOCATORE 2");
            lblRisultato.setForeground(Color.red);
            btn1.setEnabled(false);
            btn2.setEnabled(false);
            btn3.setEnabled(false);
            btn4.setEnabled(false);
            btn5.setEnabled(false);
            btn6.setEnabled(false);
            btn7.setEnabled(false);
            btn8.setEnabled(false);
            btn9.setEnabled(false);
            
            attivato = true;
            lblRestart.setText("PREMERE QUI PER GIOCARE ANCORA");
        } else if(i == 9){
            lblRisultato.setText("PAREGGIO");
            attivato = true;
            lblRestart.setText("PREMERE QUI PER GIOCARE ANCORA");
        }
    }//GEN-LAST:event_btn7ActionPerformed

    private void lblRestartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRestartMouseClicked
        // TODO add your handling code here:
        if(attivato == true){
            t.resetCampo();
            i = 0;
            lblRisultato.setText("");
            lblRestart.setText("");
            
            btn1.setText("");
            btn2.setText("");
            btn3.setText("");
            btn4.setText("");
            btn5.setText("");
            btn6.setText("");
            btn7.setText("");
            btn8.setText("");
            btn9.setText("");
            
            btn1.setEnabled(true);
            btn2.setEnabled(true);
            btn3.setEnabled(true);
            btn4.setEnabled(true);
            btn5.setEnabled(true);
            btn6.setEnabled(true);
            btn7.setEnabled(true);
            btn8.setEnabled(true);
            btn9.setEnabled(true);
        }
    }//GEN-LAST:event_lblRestartMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrisForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrisForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrisForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrisForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrisForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JLabel lblRestart;
    private javax.swing.JLabel lblRisultato;
    private javax.swing.JLabel lblTitolo;
    // End of variables declaration//GEN-END:variables
}
